/**
 * Site Generator Service
 * Converts report data into a deployable static site using LLM
 */

import { ReportSection, ReportContent } from '../types';
import { generateSiteFromReport } from './geminiService';

export interface SiteGenerationOptions {
  creatorName: string;
  reportSections: ReportSection[];
  timestamp: string;
}

/**
 * Generate a complete static site from report data
 * Returns a Map of file paths to file contents
 */
export async function generateStaticSite(options: SiteGenerationOptions): Promise<Map<string, string>> {
  const files = new Map<string, string>();

  // Use LLM to generate the HTML from report sections
  const htmlContent = await generateIndexHTML(options);
  files.set('index.html', htmlContent);

  // Generate styles.css
  files.set('styles.css', generateCSS());

  // Generate _headers for Cloudflare Pages
  files.set('_headers', generateHeaders());

  return files;
}

async function generateIndexHTML(options: SiteGenerationOptions): Promise<string> {
  const { creatorName, reportSections, timestamp } = options;

  // Convert report sections to plain text for LLM
  const reportText = convertReportSectionsToText(reportSections);

  // Get the HTML template
  const template = getHTMLTemplate();

  // Use LLM to populate the template with report data
  const populatedHTML = await generateSiteFromReport(reportText, creatorName, timestamp, template);

  return populatedHTML;
}

/**
 * Convert ReportSection array to plain text for LLM processing
 */
function convertReportSectionsToText(sections: ReportSection[]): string {
  return sections.map(section => {
    const contentText = section.content.map(item => {
      if (item.type === 'p' || item.type === 'h4') {
        return item.text;
      } else if (item.type === 'ul') {
        return item.items.map(i => `• ${i}`).join('\n');
      } else if (item.type === 'tierChart') {
        return item.items.map(i => `${i.label}: ${i.value}`).join('\n');
      }
      return '';
    }).join('\n\n');

    return `## ${section.title}\n\n${contentText}`;
  }).join('\n\n---\n\n');
}

/**
 * Get the HTML template that the LLM will populate
 */
function getHTMLTemplate(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{CREATOR_NAME}} - Creator Assessment Report</title>
    <link rel="stylesheet" href="styles.css">
    <meta name="description" content="Comprehensive creator potential assessment for {{CREATOR_NAME}}">
</head>
<body>
    <div class="container">
        <!-- Hero Section -->
        <header class="hero">
            <div class="badge">Creator Assessment Report</div>
            <h1>Your <span class="gradient-text">Creator Potential</span></h1>
            <p class="subtitle">Comprehensive analysis of your market position, earning potential, and personalized growth strategy</p>
        </header>

        <!-- Main Content - LLM will populate this section -->
        <div id="report-content">
            {{REPORT_CONTENT}}
        </div>

        <!-- Footer -->
        <footer>
            <p>Generated by Creator Assessment Platform • Confidential Report</p>
            <p class="timestamp">Generated: {{TIMESTAMP}}</p>
        </footer>
    </div>
</body>
</html>`;
}

function generateCSS(): string {
  return `* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
    line-height: 1.6;
    color: #333;
    background: linear-gradient(135deg, #fef5f1 0%, #fff9f5 100%);
    min-height: 100vh;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}

.hero {
    text-align: center;
    padding: 3rem 0;
}

.badge {
    display: inline-block;
    padding: 0.5rem 1rem;
    background: rgba(255, 107, 107, 0.1);
    color: #ff6b6b;
    border-radius: 2rem;
    font-size: 0.875rem;
    font-weight: 500;
    margin-bottom: 1rem;
}

h1 {
    font-size: 3rem;
    font-weight: 700;
    margin-bottom: 1rem;
}

.gradient-text {
    background: linear-gradient(135deg, #ff6b6b 0%, #ffd93d 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

.subtitle {
    font-size: 1.125rem;
    color: #666;
    max-width: 600px;
    margin: 0 auto;
}

#report-content {
    margin: 2rem 0;
}

.report-section {
    background: white;
    border-radius: 1rem;
    padding: 2rem;
    margin: 2rem 0;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
}

.report-section h2 {
    color: #333;
    margin-bottom: 1rem;
    font-size: 1.5rem;
}

.report-section h3 {
    color: #555;
    margin: 1.5rem 0 0.75rem 0;
    font-size: 1.25rem;
}

.report-section h4 {
    color: #666;
    margin: 1rem 0 0.5rem 0;
    font-size: 1.1rem;
}

.report-section p {
    color: #555;
    line-height: 1.8;
    margin-bottom: 1rem;
}

.report-section ul {
    margin: 1rem 0;
    padding-left: 1.5rem;
}

.report-section li {
    color: #555;
    line-height: 1.8;
    margin-bottom: 0.5rem;
}

.report-section strong {
    color: #333;
    font-weight: 600;
}

footer {
    text-align: center;
    padding: 2rem 0;
    color: #999;
    font-size: 0.875rem;
}

.timestamp {
    margin-top: 0.5rem;
}

@media (max-width: 768px) {
    h1 {
        font-size: 2rem;
    }

    .container {
        padding: 1rem;
    }

    .report-section {
        padding: 1.5rem;
    }
}`;
}

function generateHeaders(): string {
  return `/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin`;
}

